export enum EquipmentEnum {
  COMPUTED_TOMOGRAPHY_SCANNER = 'computed_tomography_scanner',
  COMPUTER = 'computer',
  CONCIERGE = 'concierge',
  DEFIBRILLATOR = 'defibrillator',
  DRINKING_FOUNTAIN = 'drinking_fountain',
  ELECTROCARDIOGRAM_MACHINE = 'electrocardiogram_machine',
  ELEVATOR = 'elevator',
  LANDLINE = 'landline',
  MAGNETIC_RESONANCE_IMAGING_MACHINE = 'magnetic_resonance_imaging_machine',
  MECHANICAL_VENTILATOR = 'mechanical_ventilator',
  NEBULIZER = 'nebulizer',
  PRINTER = 'printer',
  PULSE_OXIMETER = 'pulse_oximeter',
  SPHYGMOMANOMETER = 'sphygmomanometer',
  STETHOSCOPE = 'stethoscope',
  STRETCHER = 'stretcher',
  SURVEILLANCE_SYSTEM = 'surveillance_system',
  THERMOMETER = 'thermometer',
  ULTRASOUND_MACHINE = 'ultrasound_machine',
  VITAL_SIGNS_MONITOR = 'vital_signs_monitor',
  X_RAY_MACHINE = 'x_ray_machine',
}
